---
deployment:
  tasks:
    - export DEPLOYPATH=/home/iran66998965/public_html
    - /bin/cp -r app $DEPLOYPATH
    - /bin/cp -r resources $DEPLOYPATH
    - /bin/cp -r routes $DEPLOYPATH
    - /bin/cp -r public $DEPLOYPATH
    - /bin/cp -r config $DEPLOYPATH
    - /bin/cp -r * $DEPLOYPATH